#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [8]:
print(np.version.version)

1.16.5


#### 3. Create a null vector of size 10 (★☆☆)

In [11]:
nullVector = np.zeros(10)

#### 4.  How to find the memory size of any array (★☆☆)

In [15]:
print(nullVector.nbytes)

80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
%run python -c "import numpy; numpy.info(numpy.add)"

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [17]:
vec = np.zeros(10)
vec[4] = 1
vec[4]

1.0

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [25]:
vec1 = np.arange(10,50)
vec1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [26]:
print(vec1[: : -1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [31]:
mat = np.arange(9)
mat = mat.reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [34]:
arr = np.array([1,2,0,0,4,0])

for i in range(len(arr)):
    if(arr[i] != 0):
        print(i)
        
print(arr.nonzero())        

0
1
4
(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
mat = np.identity(3)
mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
mat1 = np.random.random((3,3,3))
mat1

array([[[0.83753933, 0.58962529, 0.52746749],
        [0.11716624, 0.22602303, 0.5245498 ],
        [0.71698888, 0.44230675, 0.61327889]],

       [[0.45475254, 0.15140942, 0.47935048],
        [0.06944557, 0.42964564, 0.46242131],
        [0.33552985, 0.35026154, 0.48924744]],

       [[0.57669025, 0.75535495, 0.0214939 ],
        [0.43801843, 0.03245143, 0.50158869],
        [0.80640776, 0.92987034, 0.29282811]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [18]:
mat10 = np.random.random((10,10))
print(mat10)

maximumValue = mat10.max()
minimumValue = mat10.min()
print("The maximum value is {} and minimum value is {} ".format(maximumValue, minimumValue))

[[0.44438921 0.52304716 0.20060246 0.05133188 0.11203033 0.33781322
  0.28132055 0.54554637 0.54523566 0.71005099]
 [0.43508299 0.99179502 0.27595021 0.93168186 0.83114857 0.85090955
  0.51033798 0.39446151 0.94879626 0.15920522]
 [0.1775285  0.05369069 0.01802645 0.74299537 0.68440076 0.80250565
  0.8915491  0.86472621 0.13065842 0.3946895 ]
 [0.93255334 0.64696104 0.07033204 0.41672557 0.56777747 0.04082317
  0.49493599 0.07775229 0.19101062 0.12097947]
 [0.72817503 0.64147769 0.20903534 0.17607797 0.99035797 0.20195061
  0.11050846 0.54361024 0.47433763 0.89455296]
 [0.22594759 0.78308433 0.3436515  0.47875803 0.96163662 0.70808902
  0.43917366 0.51215158 0.00344293 0.27107109]
 [0.20709432 0.83279354 0.79373875 0.42945225 0.08540173 0.99751356
  0.83652326 0.27099764 0.57568544 0.86049635]
 [0.34843584 0.92883978 0.50695653 0.94394126 0.60845307 0.07828691
  0.16570801 0.4770387  0.70054726 0.03091955]
 [0.67736061 0.24815861 0.12025418 0.9100873  0.1814602  0.95016035
  0.33839454

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [23]:
mat30 = np.random.random(30)
print(mat30)
print("The mean value is {}".format(mat30.mean()))

[0.88500306 0.14411178 0.22426208 0.0992054  0.66576752 0.7250026
 0.66711871 0.71758636 0.61488081 0.23867003 0.16295518 0.74037063
 0.87574898 0.19375892 0.42187376 0.32680672 0.06057184 0.90419025
 0.56286622 0.3604449  0.24600699 0.17256602 0.3219151  0.41077974
 0.98223395 0.05742391 0.16807675 0.95492078 0.46534089 0.69602884]
The mean value is 0.4688829589758822


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [27]:
Z = np.ones((5,5))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [35]:
Z1 = np.ones((5,5))
#Performing padding operation
Z1 = np.pad(Z1, pad_width=1, mode='constant', constant_values=0)
print(Z1)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [37]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [57]:
mat5 = np.diag(1+np.arange(4),k=-1)
mat5

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [64]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [67]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [73]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [7]:
mat55 = np.random.random((5,5))
mat55_min, mat55_max = mat55.min(), mat55.max()
mat55 = (mat55 - mat55_min)/(mat55_max - mat55_min)
print(mat55)

[[0.33935006 0.88269676 0.84447288 0.63421896 0.01105845]
 [0.03874949 0.5636443  0.73629944 0.6670955  0.36189266]
 [0.6329619  0.19168066 0.36853351 1.         0.00511192]
 [0.66140946 0.6042004  0.77355798 0.58838803 0.        ]
 [0.12003364 0.90122278 0.08266493 0.07468397 0.71590362]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [8]:
colour = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [12]:
mat53 = np.ones((5,3))
mat32 = np.ones((3,2))
print(np.dot(mat53, mat32))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
